spring.application.name=borewell_system

#database connection
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/DMRC_Borewells
spring.datasource.username=root
spring.datasource.password=15470529
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=Ga8gncr6lclsONcDwWivnkqib3ZIRb5zG57RoiRCRdnDFSYD2Az7vKzqwAQcknnmhuB6w9IZvbQvAUAMKy9Ygn
jwt.expirationMs=86400000
